In [29]:
import pandas as pd
import numpy as np
from dateutil import parser
import psycopg

In [30]:
df=pd.read_csv("~/health_pipline/healthcare_dataset.csv")

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  str
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  str
 3   Blood Type          55500 non-null  str
 4   Medical Condition   55500 non-null  str
 5   Date of Admission   55500 non-null  str
 6   Doctor              55500 non-null  str
 7   Hospital            55500 non-null  str
 8   Insurance Provider  55500 non-null  str
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  str
 12  Discharge Date      55500 non-null  str
 13  Medication          55500 non-null  str
 14  Test Results        55500 non-null  str
dtypes: float64(1), int64(2), str(12)
memory usage: 6.4 MB

In [32]:
df.dtypes

Name                      str
Age                     int64
Gender                    str
Blood Type                str
Medical Condition         str
Date of Admission         str
Doctor                    str
Hospital                  str
Insurance Provider        str
Billing Amount        float64
Room Number             int64
Admission Type            str
Discharge Date            str
Medication                str
Test Results              str
dtype: object

In [33]:
df.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [34]:
df.duplicated().sum()

np.int64(534)

In [35]:
df.describe()

                Age  Billing Amount   Room Number
count  55500.000000    55500.000000  55500.000000
mean      51.539459    25539.316097    301.134829
std       19.602454    14211.454431    115.243069
min       13.000000    -2008.492140    101.000000
25%       35.000000    13241.224652    202.000000
50%       52.000000    25538.069376    302.000000
75%       68.000000    37820.508436    401.000000
max       89.000000    52764.276736    500.000000

In [36]:
df["Name"].sample(20)
df["Gender"].unique()
df["Blood Type"].unique()
df["Medical Condition"].unique()
df["Doctor"].sample(20)
df["Hospital"].sample(20)
df["Insurance Provider"].unique()
df["Admission Type"].unique()
df["Medication"].unique()
df["Test Results"].unique()

<StringArray>
['Normal', 'Inconclusive', 'Abnormal']
Length: 3, dtype: str

In [37]:
#remove the duplicates 
df=df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [38]:
#Change the categorical columns to lowercase
df_col=["Name","Gender","Blood Type","Medical Condition","Doctor","Hospital","Insurance Provider",\
    "Admission Type","Medication","Test Results"]

for col in df_col:
    df[col]=df[col].str.lower().str.strip()

In [39]:
#Handling the negaitve billing amounts
df["Billing Amount"]=df["Billing Amount"].abs()

In [40]:
#Changing the Date columns to date types
df["Date of Admission"]=pd.to_datetime(df["Date of Admission"])
df["Discharge Date"]=pd.to_datetime(df["Discharge Date"])

In [41]:
df.dtypes

Name                             str
Age                            int64
Gender                           str
Blood Type                       str
Medical Condition                str
Date of Admission     datetime64[us]
Doctor                           str
Hospital                         str
Insurance Provider               str
Billing Amount               float64
Room Number                    int64
Admission Type                   str
Discharge Date        datetime64[us]
Medication                       str
Test Results                     str
dtype: object

In [42]:
#Handling patient name (firstName,lastName)
df[["patient_title","name"]]=df["Name"].str.extract(r'^(?:([A-Za-z]+)\.\s*)?(.*)')
df[["first","middle","last"]]=df["Name"].str.extract(r'([A-Za-z]+)\s+([A-Za-z]\.)?\s*([A-Za-z]+)')
df["Name"]=df["first"] + " " + df["last"]
# drop the reduntant columns 
df=df.drop(["name","first","middle","last"],axis=1)

In [43]:
#Handling Doctor name (firstName,lastName)
df[["doctor_title","name"]]=df["Doctor"].str.extract(r'^(?:([A-Za-z]+)\.\s*)?(.*)')
df[["first","middle","last"]]=df["Doctor"].str.extract(r'([A-Za-z]+)\s+([A-Za-z]\.)?\s*([A-Za-z]+)')
df["Doctor"]=df["first"] + " " + df["last"]
# drop the reduntant columns 
df=df.drop(["name","first","middle","last","doctor_title"],axis=1)

In [44]:
#handling Hospital names
df["Hospital"] = df["Hospital"].str.replace(r"\band\b|,", "", regex=True)
df["Hospital"] = df["Hospital"].str.replace(r"\s+|-", " ", regex=True)
df["Hospital"] = df["Hospital"].str.strip()

In [45]:
#handling column names
df.columns=df.columns.str.lower().str.replace(' ','_')
df

,name,age,gender,blood_type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results,patient_title
0,bobby jackson,30,male,b-,cancer,2024-01-31,matthew smith,sons miller,blue cross,18856.281306,328,urgent,2024-02-02,paracetamol,normal,NaN
1,leslie terry,62,male,a+,obesity,2019-08-20,samantha davies,kim inc,medicare,33643.327287,265,emergency,2019-08-26,ibuprofen,inconclusive,NaN
2,danny smith,76,female,a-,obesity,2022-09-22,tiffany mitchell,cook plc,aetna,27955.096079,205,emergency,2022-10-07,aspirin,normal,NaN
3,andrew watts,28,female,o+,diabetes,2020-11-18,kevin wells,hernandez rogers vang,medicare,37909.782410,450,elective,2020-12-18,ibuprofen,abnormal,NaN
4,adrienne bell,43,female,ab+,cancer,2022-09-19,kathleen hanna,white white,aetna,14238.317814,458,urgent,2022-10-09,penicillin,abnormal,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,elizabeth jackson,42,female,o+,asthma,2020-08-16,joshua jarvis,jones thompson,blue cross,2650.714952,417,elective,2020-09-15,penicillin,abnormal,NaN
55496,kyle perez,61,female,ab-,obesity,2020-01-23,taylor sullivan,tucker moyer,cigna,31457.797307,316,elective,2020-02-01,aspirin,normal,NaN
55497,heather wang,38,female,b+,hypertension,2020-07-13,joe jacobs,mahoney johnson vasquez,unitedhealthcare,27620.764717,347,urgent,2020-08-10,ibuprofen,abnormal,NaN
55498,jennifer jones,43,male,o-,arthritis,2019-05-25,kimberly curry,jackson todd castro,medicare,32451.092358,321,elective,2019-05-31,ibuprofen,abnormal,NaN
55499,james garcia,53,female,o+,arthritis,2024-04-02,dennis warren,henry sons,aetna,4010.134172,448,urgent,2024-04-29,ibuprofen,abnormal,NaN

In [46]:
df.to_csv("~/health_pipline/healthcare_cleaned.csv",index=False)

In [47]:
conn_str = "dbname=medical user=postgres password=postgres host=localhost port=5432"
doctor_df = df[["doctor"]].drop_duplicates()
hospital_df = df[["hospital"]].drop_duplicates()
patient_df = df[["name","age", "gender", "blood_type", "insurance_provider","patient_title"]].drop_duplicates(subset=["name","age","gender","blood_type","insurance_provider"])

with psycopg.connect(conn_str) as conn:
    with conn.cursor() as cur:

        # doctor
        with cur.copy("COPY doctor (name) FROM STDIN") as copy:
            for row in doctor_df.itertuples(index=False, name=None):
                copy.write_row(row)

        # hospital
        with cur.copy("COPY hospital (name) FROM STDIN") as copy:
            for row in hospital_df.itertuples(index=False, name=None):
                copy.write_row(row)

        # patient
        with cur.copy("COPY patient (name,age, gender, blood_type, insurance_provider,patient_title) FROM STDIN") as copy:
            for row in patient_df.itertuples(index=False, name=None):
                copy.write_row(row)

In [48]:
with psycopg.connect(conn_str) as conn:
    patient=pd.read_sql_query("""select * from patient""",conn)
    doctor=pd.read_sql_query("""select * from doctor""",conn)
    hospital=pd.read_sql_query("""select * from hospital""",conn)

/tmp/ipykernel_12704/1860832911.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  patient=pd.read_sql_query("""select * from patient""",conn)
/tmp/ipykernel_12704/1860832911.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  doctor=pd.read_sql_query("""select * from doctor""",conn)
/tmp/ipykernel_12704/1860832911.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  hospital=pd.read_sql_query("""select * from hospital""",conn)

In [49]:
doctor = doctor.rename(
    columns={
        "doctor_id": "doctor_id",
        "name": "doctor_name"
    }
)

hospital = hospital.rename(
    columns={
        "hospital_id": "hospital_id",
        "name": "hospital_name"
    }
)

patient = patient.rename(
    columns={
        "patient_id": "patient_id",
        "name": "patient_name"
    }
)

In [50]:
df = df.merge(
    doctor,
    left_on="doctor",
    right_on="doctor_name",
    how="left"
)

In [51]:
df = df.merge(
    hospital,
    left_on="hospital",
    right_on="hospital_name",
    how="left"
)

In [52]:
df

,name,age,gender,blood_type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results,patient_title,doctor_id,doctor_name,hospital_id,hospital_name
0,bobby jackson,30,male,b-,cancer,2024-01-31,matthew smith,sons miller,blue cross,18856.281306,328,urgent,2024-02-02,paracetamol,normal,NaN,1,matthew smith,1,sons miller
1,leslie terry,62,male,a+,obesity,2019-08-20,samantha davies,kim inc,medicare,33643.327287,265,emergency,2019-08-26,ibuprofen,inconclusive,NaN,2,samantha davies,2,kim inc
2,danny smith,76,female,a-,obesity,2022-09-22,tiffany mitchell,cook plc,aetna,27955.096079,205,emergency,2022-10-07,aspirin,normal,NaN,3,tiffany mitchell,3,cook plc
3,andrew watts,28,female,o+,diabetes,2020-11-18,kevin wells,hernandez rogers vang,medicare,37909.782410,450,elective,2020-12-18,ibuprofen,abnormal,NaN,4,kevin wells,4,hernandez rogers vang
4,adrienne bell,43,female,ab+,cancer,2022-09-19,kathleen hanna,white white,aetna,14238.317814,458,urgent,2022-10-09,penicillin,abnormal,NaN,5,kathleen hanna,5,white white
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54961,elizabeth jackson,42,female,o+,asthma,2020-08-16,joshua jarvis,jones thompson,blue cross,2650.714952,417,elective,2020-09-15,penicillin,abnormal,NaN,22330,joshua jarvis,21662,jones thompson
54962,kyle perez,61,female,ab-,obesity,2020-01-23,taylor sullivan,tucker moyer,cigna,31457.797307,316,elective,2020-02-01,aspirin,normal,NaN,801,taylor sullivan,793,tucker moyer
54963,heather wang,38,female,b+,hypertension,2020-07-13,joe jacobs,mahoney johnson vasquez,unitedhealthcare,27620.764717,347,urgent,2020-08-10,ibuprofen,abnormal,NaN,1865,joe jacobs,1839,mahoney johnson vasquez
54964,jennifer jones,43,male,o-,arthritis,2019-05-25,kimberly curry,jackson todd castro,medicare,32451.092358,321,elective,2019-05-31,ibuprofen,abnormal,NaN,22556,kimberly curry,21891,jackson todd castro
54965,james garcia,53,female,o+,arthritis,2024-04-02,dennis warren,henry sons,aetna,4010.134172,448,urgent,2024-04-29,ibuprofen,abnormal,NaN,7026,dennis warren,4618,henry sons

In [53]:
df = df.merge(
    patient,
    left_on=[
        "name",
        "age",
        "blood_type",
        "insurance_provider"
    ],
    right_on=[
        "patient_name",
        "age",
        "blood_type",
        "insurance_provider"
    ],
    how="left"
)

In [54]:
df

,name,age,gender_x,blood_type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,...,test_results,patient_title_x,doctor_id,doctor_name,hospital_id,hospital_name,patient_id,patient_name,gender_y,patient_title_y
0,bobby jackson,30,male,b-,cancer,2024-01-31,matthew smith,sons miller,blue cross,18856.281306,...,normal,NaN,1,matthew smith,1,sons miller,1,bobby jackson,male,nan
1,leslie terry,62,male,a+,obesity,2019-08-20,samantha davies,kim inc,medicare,33643.327287,...,inconclusive,NaN,2,samantha davies,2,kim inc,2,leslie terry,male,nan
2,danny smith,76,female,a-,obesity,2022-09-22,tiffany mitchell,cook plc,aetna,27955.096079,...,normal,NaN,3,tiffany mitchell,3,cook plc,3,danny smith,female,nan
3,andrew watts,28,female,o+,diabetes,2020-11-18,kevin wells,hernandez rogers vang,medicare,37909.782410,...,abnormal,NaN,4,kevin wells,4,hernandez rogers vang,4,andrew watts,female,nan
4,adrienne bell,43,female,ab+,cancer,2022-09-19,kathleen hanna,white white,aetna,14238.317814,...,abnormal,NaN,5,kathleen hanna,5,white white,5,adrienne bell,female,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54971,elizabeth jackson,42,female,o+,asthma,2020-08-16,joshua jarvis,jones thompson,blue cross,2650.714952,...,abnormal,NaN,22330,joshua jarvis,21662,jones thompson,54959,elizabeth jackson,female,nan
54972,kyle perez,61,female,ab-,obesity,2020-01-23,taylor sullivan,tucker moyer,cigna,31457.797307,...,normal,NaN,801,taylor sullivan,793,tucker moyer,54960,kyle perez,female,nan
54973,heather wang,38,female,b+,hypertension,2020-07-13,joe jacobs,mahoney johnson vasquez,unitedhealthcare,27620.764717,...,abnormal,NaN,1865,joe jacobs,1839,mahoney johnson vasquez,54961,heather wang,female,nan
54974,jennifer jones,43,male,o-,arthritis,2019-05-25,kimberly curry,jackson todd castro,medicare,32451.092358,...,abnormal,NaN,22556,kimberly curry,21891,jackson todd castro,54962,jennifer jones,male,nan
54975,james garcia,53,female,o+,arthritis,2024-04-02,dennis warren,henry sons,aetna,4010.134172,...,abnormal,NaN,7026,dennis warren,4618,henry sons,54963,james garcia,female,nan

In [55]:
df_visit=df[["patient_id","doctor_id","hospital_id","date_of_admission","discharge_date","admission_type","medical_condition","billing_amount","medication","test_results","room_number"]]

In [56]:
with psycopg.connect(conn_str) as conn:
    with conn.cursor() as cur:
        with cur.copy("COPY visit (patient_id,doctor_id,hospital_id,date_of_admission,discharge_date,admission_type,medical_condition,billing_amount,medication,test_results,room_number) FROM STDIN") as copy:
            for row in df_visit.itertuples(index=False, name=None):
                copy.write_row(row)

In [57]:
df.sample(50)

,name,age,gender_x,blood_type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,...,test_results,patient_title_x,doctor_id,doctor_name,hospital_id,hospital_name,patient_id,patient_name,gender_y,patient_title_y
51549,michael sandoval,72,female,ab-,cancer,2023-07-27,scott hayes,sons bond,aetna,40932.204414,...,inconclusive,NaN,6098,scott hayes,5594,sons bond,51538,michael sandoval,female,nan
53222,samuel maldonado,42,female,o+,obesity,2023-10-09,tara kennedy,lopez lewis carr,aetna,43316.385739,...,abnormal,NaN,38260,tara kennedy,37762,lopez lewis carr,53211,samuel maldonado,female,nan
6806,candace schroeder,23,female,a-,asthma,2020-09-23,eric ball,anderson norris,cigna,47854.586015,...,abnormal,NaN,6497,eric ball,6311,anderson norris,6806,candace schroeder,female,nan
45428,stephen morrow,79,female,ab+,asthma,2020-07-22,rebecca morales,brown garcia,cigna,6467.062334,...,normal,NaN,36586,rebecca morales,35980,brown garcia,45419,stephen morrow,female,nan
30020,dustin alexander,69,male,b-,hypertension,2022-10-18,paul solis,bradshaw herrera cook,blue cross,16732.225643,...,inconclusive,NaN,25610,paul solis,24875,bradshaw herrera cook,30016,dustin alexander,male,nan
39398,sarah torres,67,male,ab-,cancer,2019-07-03,calvin nunez,roberts diaz,medicare,39117.954611,...,abnormal,NaN,32442,calvin nunez,31544,roberts diaz,39391,sarah torres,male,nan
49711,grace garcia,29,male,ab+,asthma,2020-02-27,kendra graves,myers west,aetna,14385.167817,...,abnormal,NaN,39498,kendra graves,39060,myers west,49701,grace garcia,male,nan
29131,allison sawyer,63,female,b-,asthma,2022-03-11,joshua wilson,bell ortiz,aetna,3275.584877,...,normal,NaN,4148,joshua wilson,24236,bell ortiz,29127,allison sawyer,female,nan
48995,michael henry,56,male,b+,arthritis,2023-01-06,wesley barnes,lloyd parker barrett,blue cross,13754.577943,...,inconclusive,NaN,39013,wesley barnes,38533,lloyd parker barrett,48985,michael henry,male,nan
8700,debbie thomas,28,female,o-,diabetes,2020-08-08,nicholas mack,nguyen monroe gomez,aetna,34105.143572,...,abnormal,ms,8214,nicholas mack,7941,nguyen monroe gomez,8700,debbie thomas,female,ms
9714,leslie gentry,38,female,ab-,diabetes,2022-07-26,travis schultz,mclaughlin bernard pearson,cigna,19858.670319,...,inconclusive,NaN,9112,travis schultz,8820,mclaughlin bernard pearson,9714,leslie gentry,female,nan
19239,taylor davila,43,female,a+,hypertension,2019-07-22,anthony graves,johnson group,unitedhealthcare,11583.981533,...,inconclusive,NaN,433,anthony graves,218,johnson group,19236,taylor davila,female,nan
28966,gavin baker,64,male,a-,hypertension,2021-09-06,steven randall,craig llc,cigna,23247.438653,...,abnormal,NaN,24555,steven randall,24118,craig llc,28962,gavin baker,male,nan
13384,tina ramirez,49,male,o+,cancer,2020-03-15,emily moore,haynes llc,blue cross,12920.188842,...,abnormal,NaN,12309,emily moore,11906,haynes llc,13383,tina ramirez,male,nan
23594,sharon peterson,77,male,a-,hypertension,2020-07-30,nicholas wong,gonzalez moreno anderson,cigna,48327.459309,...,inconclusive,NaN,20709,nicholas wong,20045,gonzalez moreno anderson,23590,sharon peterson,male,nan
35829,hunter lawrence,42,female,o-,arthritis,2020-11-28,tiffany james,williams esparza,blue cross,19353.520501,...,inconclusive,NaN,29895,tiffany james,29134,williams esparza,35822,hunter lawrence,female,nan
39600,vincent bailey,37,female,a+,arthritis,2020-11-09,dennis hopkins,mcconnell group,medicare,40694.938761,...,abnormal,NaN,32575,dennis hopkins,31867,mcconnell group,39593,vincent bailey,female,nan
50811,kathy jones,45,male,o-,hypertension,2020-04-13,jared stone,jacobs smith,aetna,23130.705056,...,abnormal,NaN,9011,jared stone,8722,jacobs smith,50801,kathy jones,male,nan
26998,carolyn vaughn,22,female,o-,arthritis,2020-09-04,terry vaughn,wheeler garcia garcia,aetna,6723.343153,...,abnormal,dr,23337,terry vaughn,22635,wheeler garcia garcia,26994,carolyn vaughn,female,dr
27527,howard torres,69,female,a-,hypertension,2024-04-17,charles strong,richardson curtis moore,unitedhealthcare,8689.873336,...,normal,NaN,23740,charles strong,23029,richardson curtis moore,27523,howard torres,female,nan
29512,kara lee,33,male,o+,obesity,2023-10-06,todd li,hernandez inc,medicare,43393.002049,...,normal,NaN,25215,todd li,11511,hernandez inc,29508,kara lee,male,nan
27581,edward brooks,25,female,ab+,asthma,2022-09-21,john nunez,herman williams parker,cigna,37751.088993,...,inconclusive,NaN,23774,john nunez,23076,herman williams parker,27577,edward brooks,female,nan
53681,donald snow,78,female,o+,diabetes,2019-09-10,destiny miller,lee sons,unitedhealthcare,14270.038761,...,inconclusive,NaN,11948,destiny miller,1177,lee sons,53670,donald snow,female,nan
26517,joseph young,36,female,o-,asthma,2021-07-26,sarah golden,group murphy,aetna,10040.175258,...,normal,NaN,22957,sarah golden,5440,group murphy,26513,joseph young,female,nan
54853,susan kelley,33,female,a+,diabetes,2020-05-04,dana campbell,brown group,aetna,34358.836548,...,normal,NaN,34863,dana campbell,6418,brown group,54841,susan kelley,female,nan
44289,lori wood,53,female,o+,cancer,2022-10-23,jacqueline kelly,ewing baker,aetna,48002.410476,...,inconclusive,NaN,35809,jacqueline kelly,35196,ewing baker,44281,lori wood,female,nan
120,anne howell,22,female,a-,obesity,2022-08-22,patrick carter,cline carpenter,blue cross,23499.936251,...,normal,NaN,121,patrick carter,121,cline carpenter,121,anne howell,female,nan
28093,christopher serrano,70,male,b-,obesity,2019-09-01,thomas schwartz,huber llc,aetna,6959.339626,...,inconclusive,NaN,1314,thomas schwartz,23452,huber llc,28089,christopher serrano,male,nan
11521,robin walker,38,female,b-,asthma,2021-01-22,brittany aguirre,mooney clark,cigna,3334.481536,...,abnormal,NaN,10683,brittany aguirre,10343,mooney clark,11520,robin walker,female,nan
6462,hunter mendoza,44,male,o+,hypertension,2022-06-19,jonathan lane,thomas bradley,aetna,24336.105280,...,normal,NaN,6186,jonathan lane,6009,thomas bradley,6462,hunter mendoza,male,nan
21698,daniel keller,55,male,o+,cancer,2023-09-10,jacob mendez,moore goodwin,cigna,18328.533691,...,inconclusive,NaN,19203,jacob mendez,18551,moore goodwin,21695,daniel keller,male,nan
16748,george howell,82,male,o-,hypertension,2021-03-23,crystal price,hart ferguson,aetna,3267.339631,...,inconclusive,NaN,15167,crystal price,14591,hart ferguson,16745,george howell,male,nan
17196,brandon cooper,52,female,ab-,diabetes,2023-04-28,ashley hardy,llc bennett,blue cross,29417.314374,...,abnormal,NaN,15537,ashley hardy,2765,llc bennett,17193,brandon cooper,female,nan
41818,scott cannon,46,female,a+,hypertension,2024-05-01,lori jensen,mendoza meyer massey,cigna,48224.544068,...,abnormal,NaN,34105,lori jensen,33426,mendoza meyer massey,41811,scott cannon,female,nan
43149,jonathan allen,34,female,a-,asthma,2022-02-15,frank guerrero,wright wright gardner,cigna,28605.680976,...,abnormal,NaN,35017,frank guerrero,34394,wright wright gardner,43142,jonathan allen,female,nan
23319,karen thomas,68,male,a-,arthritis,2019-07-10,monica santana,moore harrell,blue cross,41168.233014,...,abnormal,NaN,2495,monica santana,19814,moore harrell,23315,karen thomas,male,nan
11490,billy morgan,34,female,b-,asthma,2021-04-21,katherine williams,buchanan jones,blue cross,30448.788861,...,inconclusive,NaN,10656,katherine williams,10319,buchanan jones,11489,billy morgan,female,nan
10830,william cunningham,26,male,a-,hypertension,2020-11-10,william johnson,stevens sanchez,medicare,37191.507641,...,inconclusive,NaN,2982,william johnson,9763,stevens sanchez,10829,william cunningham,male,nan
21935,allen pierce,72,male,a+,cancer,2021-12-25,julia jenkins,berry group,unitedhealthcare,27898.683488,...,inconclusive,NaN,19400,julia jenkins,4907,berry group,21932,allen pierce,male,nan
37397,michael smith,62,female,o-,cancer,2020-12-30,kathryn stewart,huynh plc,medicare,25818.972232,...,abnormal,NaN,30995,kathryn stewart,30265,huynh plc,37390,michael smith,female,nan
13902,paul guerrero,58,female,ab+,diabetes,2020-03-03,andrea rodgers,hall woods johnson,cigna,3649.433404,...,normal,NaN,12748,andrea rodgers,12314,hall woods johnson,13900,paul guerrero,female,nan
38311,patrick sandoval,77,female,o-,hypertension,2019-10-22,patrick mckee,phillips ltd,cigna,9901.957346,...,normal,NaN,31666,patrick mckee,826,phillips ltd,38304,patrick sandoval,female,nan
24703,natalie smith,82,female,ab+,hypertension,2019-10-02,david weiss,johnson rosario,blue cross,40926.778846,...,abnormal,NaN,21569,david weiss,20889,johnson rosario,24699,natalie smith,female,nan
11292,maria costa,36,female,ab+,obesity,2021-12-27,justin mcdaniel,ltd henry,aetna,39172.983300,...,inconclusive,NaN,10482,justin mcdaniel,2536,ltd henry,11291,maria costa,female,nan
29489,keith graham,79,female,b-,hypertension,2021-03-03,marcia yoder,ward jones jackson,cigna,47913.133884,...,inconclusive,NaN,25197,marcia yoder,24486,ward jones jackson,29485,keith graham,female,nan
43083,drew castaneda,21,female,a+,obesity,2021-06-18,melissa diaz,chavez jenkins davidson,cigna,19083.242838,...,inconclusive,NaN,34973,melissa diaz,34341,chavez jenkins davidson,43076,drew castaneda,female,nan
40293,jennifer weber,45,male,b-,obesity,2021-04-21,holly martinez,mills schroeder edwards,unitedhealthcare,37530.116430,...,inconclusive,NaN,33047,holly martinez,32351,mills schroeder edwards,40286,jennifer weber,male,nan
53105,michelle gonzalez,37,male,o+,asthma,2021-12-25,dustin miller,reed davis rodriguez,cigna,42634.010325,...,normal,NaN,19297,dustin miller,18644,reed davis rodriguez,53094,michelle gonzalez,male,nan
24261,tanya taylor,82,male,ab-,hypertension,2023-01-02,chad walker,higgins baker dalton,blue cross,28892.638534,...,normal,NaN,21218,chad walker,20547,higgins baker dalton,24257,tanya taylor,male,nan
43363,joshua ho,53,male,ab-,arthritis,2019-10-11,christopher murray,goodman miller,cigna,41354.899000,...,inconclusive,NaN,5401,christopher murray,34538,goodman miller,43356,joshua ho,male,nan